### PR TITLE
ok?

### PR DESCRIPTION
**Pull request by oleg-pahl**

### CODE REVIEW

**Comment by oleg-pahl** [comment]
fix debhelper compatibility

**Comment by alexander-naumov** [comment]
Yes, this commit https://github.com/alexander-naumov/pam-accesscontrol/pull/21/commits/551d4d7dd7b2c86deb076876afe26adafb803f31 is ok.

**Comment by oleg-pahl** [comment]
> Please always provide some short explanation...
> 
> In this case: [6b906fa](https://github.com/alexander-naumov/pam-accesscontrol/commit/6b906fa6c9f671744ed61666d5674745f68b595c)
> Why do you think it's better to do it in prerm and not in postrm?

**Postinst corresponds to prerm, not postrm**

**Comment by alexander-naumov** [comment]
> **Postinst corresponds to prerm, not postrm**

Postinst? There is nothing about postinst. We're talking about prerm VS postrm...

Please read official manual: 
https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html

**Pull request closed without merging**
