### PR TITLE
Development

### PR DESCRIPTION
**Pull request by oleg-pahl**
Hi, 

could you be so kind to approve my pull request?

BR
Oleg Pahl

### CODE REVIEW

**Comment by oleg-pahl** [comment]
Hi,
With last commit I try to update comparison to True
ok?

**Comment by oleg-pahl** [comment]
ok?

**Comment by oleg-pahl** [comment]
Hi,
occurs when an except clause doesn't specify exceptions type to catch.
ok?

**Comment by oleg-pahl** [comment]
Python3's range is Python2's xrange.

**Comment by alexander-naumov** [comment]
Hi,
well, yes, I like your patches. Thank you very much for your code.

...except of https://github.com/alexander-naumov/pam-accesscontrol/pull/7/commits/d125bddc3276a9972e60f236b2646804312c957e.
`if show True:`
this is definitely invalid syntax.

Change if back please and I will accept your pull request ;-)

**Comment by alexander-naumov** [comment]
Good changes, but at least 2 new exceptions... closed.

**Pull request closed without merging**
